version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-list-aws-default"  # Cambiado para evitar conflicto con otros entornos
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"default\""
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "todo-list-aws-staging"  # Nombre de stack exclusivo para el entorno de staging
s3_bucket = "aws-sam-cli-managed-staging-samclisourcebucket-upt09go84tay"
s3_prefix = "todo-list-aws"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"staging\""
image_repositories = []




