version = "0.1"

[default]
stack_name = "todo-list-production"
capabilities = "CAPABILITY_IAM"
region = "us-west-2"
table_name = "todos-production"  # Nombre de la tabla para el entorno de producción

